version: "3"
services: 
    user-service:
        build: "./User-Service"
        depends_on: 
            - user-service-mongo
        volumes:
            - ./User-Service:/opt/app
    user-service-mongo:
        image: mongo
        ports: 
            - 27017:27017
        environment:
            MONGO_INITDB_DATABASE: users
            MONGO_INITDB_USER_NAME: root
            MONGO_INITDB_PASSWORD: toor
    task-service:
        build: "./Task-Service"
        depends_on: 
            - task-service-mongo
        volumes:
            - ./Task-Service:/opt/app
    task-service-mongo:
        image: mongo
        ports: 
            - 27018:27017
        environment:
            MONGO_INITDB_DATABASE: tasks
            MONGO_INITDB_USER_NAME: root
            MONGO_INITDB_PASSWORD: toor
    tasklist-service:
        build: "./TaskList-Service"
        depends_on: 
            - tasklist-service-mongo
        volumes:
            - ./TaskList-Service:/opt/app
    tasklist-service-mongo:
        image: mongo
        ports: 
            - 27019:27017
        environment:
            MONGO_INITDB_DATABASE: tasklists
            MONGO_INITDB_USER_NAME: root
            MONGO_INITDB_PASSWORD: toor
