version: "3"
services: 
    user-service:
        build: "./user-service"
        depends_on:
            - user-service-mongo-db
            - user-service-mongo-express
        volumes:
            - ./user-service:/opt/app
    user-service-mongo-db:
        image: mongo
        restart: always
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    user-service-mongo-express:
        image: mongo-express
        restart: always
        ports:
            [8081:8081]
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: ''
            ME_CONFIG_BASICAUTH_PASSWORD: ''
            ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
            ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
            ME_CONFIG_MONGODB_ADMINPASSWORD: 'toor'
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_SERVER: 'mongo'
            ME_CONFIG_OPTIONS_EDITORTHEME: 'default'
            ME_CONFIG_REQUEST_SIZE: '100kb'
            ME_CONFIG_SITE_BASEURL: '/'
            ME_CONFIG_SITE_COOKIESECRET: 'cookiesecret'
            ME_CONFIG_SITE_SESSIONSECRECT: 'sessionsecret'
            ME_CONFIG_SITE_SSL_ENABLED: 'false'
            ME_CONFIG_SITE_SSL_CRT_PATH: ''
            ME_CONFIG_SITE_SSL_KEY_PATH: ''
    task-service:
        build: "./task-service"
        depends_on: 
            - task-service-mongo-db
            - task-service-mongo-express
        volumes:
            - ./task-service:/opt/app
    task-service-mongo-db:
        image: mongo
        restart: always
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    task-service-mongo-express:
        image: mongo-express
        restart: always
        ports:
            [8082:8082]
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: ''
            ME_CONFIG_BASICAUTH_PASSWORD: ''
            ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
            ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
            ME_CONFIG_MONGODB_ADMINPASSWORD: 'toor'
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_SERVER: 'mongo'
            ME_CONFIG_OPTIONS_EDITORTHEME: 'default'
            ME_CONFIG_REQUEST_SIZE: '100kb'
            ME_CONFIG_SITE_BASEURL: '/'
            ME_CONFIG_SITE_COOKIESECRET: 'cookiesecret'
            ME_CONFIG_SITE_SESSIONSECRECT: 'sessionsecret'
            ME_CONFIG_SITE_SSL_ENABLED: 'false'
            ME_CONFIG_SITE_SSL_CRT_PATH: ''
            ME_CONFIG_SITE_SSL_KEY_PATH: ''
    tasklist-service:
        build: "./tasklist-service"
        depends_on: 
            - tasklist-service-mongo-db
            - tasklist-service-mongo-express
        volumes:
            - ./taslkist-service:/opt/app
    tasklist-service-mongo-db:
        image: mongo
        restart: always
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    tasklist-service-mongo-express:
        image: mongo-express
        restart: always
        ports:
            [8083:8083]
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: ''
            ME_CONFIG_BASICAUTH_PASSWORD: ''
            ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
            ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
            ME_CONFIG_MONGODB_ADMINPASSWORD: 'toor'
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_SERVER: 'mongo'
            ME_CONFIG_OPTIONS_EDITORTHEME: 'default'
            ME_CONFIG_REQUEST_SIZE: '100kb'
            ME_CONFIG_SITE_BASEURL: '/'
            ME_CONFIG_SITE_COOKIESECRET: 'cookiesecret'
            ME_CONFIG_SITE_SESSIONSECRECT: 'sessionsecret'
            ME_CONFIG_SITE_SSL_ENABLED: 'false'
            ME_CONFIG_SITE_SSL_CRT_PATH: ''
            ME_CONFIG_SITE_SSL_KEY_PATH: ''
            